version: "3"
services:
  flagd:
    image: "ghcr.io/open-feature/flagd:latest"
    ports:
      - "8013:8013"
    command: ["start", "--uri", "file:./etc/flagd/flags.flagd.json"]
    volumes:
      - ./flags:/etc/flagd
volumes:
  flags: