version: "3"
services:
  postgres:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=unleash_user
      - POSTGRES_PASSWORD=unleash_password
      - POSTGRES_DB=unleash
    networks:
      - unleash
  unleash:
    image: "unleashorg/unleash-server:latest"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=unleash
      - DATABASE_USERNAME=unleash_user
      - DATABASE_PASSWORD=unleash_password
      - DATABASE_SSL=false
    ports:
      - "4242:4242"
    networks:
      - unleash
networks:
  unleash: